name: "Julian's Webpage"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#42157a'
    - '#ffffff'
    - '#010101'
    - '#928c98'
    - '#c7c8cd'
  brandStrength: 0.7863718224689364
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
